---
################################ BASE INFO ##########################

# 远程临时目录
TOOLS_TMP_DIR: "/tmp"

# run work
RUN_WORK: "/var/run"

# bin work
BIN_WORK: "/usr/local/bin"

# systemd service work
SYSTEM_SERVICE_WORK: "/usr/lib/systemd/system"

################################ CLUSTER INFO ##########################

# inventory group name
# 配置为ansible hosts 文件的组名必须为如下，自定义的其他应用除外
#   也就是说SITE_INFO下面一层的如下配置必须为固定, 还有ip字段
# k8s_master
# k8s_work
# etcd
# proxy

# ansible hosts childre group
# 组嵌套CHILDREN下面一层的如下配置必须为固定
CHILDREN:
  cluster:
    children: [docker, k8s_work]

# SITE_INFO 下面一层不能改变
SITE_INFO:
  docker_node:
    docker01:
      ip: 192.168.3.24
    docker02:
      ip: 192.168.3.25
    docker03:
      ip: 192.168.3.26

  harbor_node:
    harbor01:
      ip: 192.168.3.24

################################ DOCKER ##########################
# docker  systemd or  cgroupfs
CGROUP_DRIVE: "cgroupfs"

# docker cn registries
CN_REGISTRY: ["https://registry.docker-cn.com"]

# docker insecure-registries 默认禁用
# INSECURE_REGISTRIES: ["myregistrydomain.com:5000"]

# docker version 18.03.1.ce-1.el7.centos
DOCKER_VERSION: "18.03.1.ce-1.el7.centos"

# docker work dir default /var/lib/docker
# 当启用了此项配置，会为docker配置data目录指向
DOCKER_WORK: "/data/docker"

# 是否删除docker的data目录
DOCKER_WORK_CLEAN: false

################################ DOCKER HARBOR ##########################
# harbor work
DOCKER_HARBOR_WORK: ""

# harbor hostname
DOCKER_HARBOR_HOSTNAME: ""

# ui_url_protocol http/https
DOCKER_HARBOR_PROTOCOL: "http"

# harbor job workers defult 10 max_job_workers
DOCKER_HARBOR_WORKERS: 10

# harbor harbor_admin_password
DOCKER_HARBOR_PASSWORD: "Harbor12345"

# ssl_cert path
DOCKER_HARBOR_SSL_CERT: "/data/cert/server.crt"

# ssl_cert_key path
DOCKER_HARBOR_SSL_CERT_KEY: "/data/cert/server.key"

################################ TIME INFO ##########################
# set time tag
# 默认支持配置系统时间同步
TIME:
  tag: true
  server: "0.centos.pool.ntp.org"

################################ KERNEL INFO ##########################
# kernetl tag default false, if you want to update kernel; need set it true
# 程序提供升级Linux内核为最新，默认关闭
KERNEL_TAG: false
