---
################################ BASE INFO ##########################

# 远程临时目录
TOOLS_TMP_DIR: "/tmp"

# run work
RUN_WORK: "/var/run"

# bin work
BIN_WORK: "/usr/local/bin"

# systemd service work
SYSTEM_SERVICE_WORK: "/usr/lib/systemd/system"

################################ CLUSTER INFO ##########################

# inventory group name
# 配置为ansible hosts 文件的组名必须为如下，自定义的其他应用除外
#   也就是说SITE_INFO下面一层的如下配置必须为固定, 还有ip字段
# k8s_master
# k8s_work
# etcd
# proxy

# ansible hosts childre group
# 组嵌套CHILDREN下面一层的如下配置必须为固定
CHILDREN:
  k8s_node:
    children: [k8s_master, k8s_work]
  cluster_node:
    children: [k8s_master, k8s_work, proxy, etcd]

# 服务器hosts文件生成依赖SIT_INFO配置,但是最终控制hosts需要生成的信息,是如下配置
# HOSTS_LIST: [k8s_master, k8s_work, proxy, etcd, k8s_work_add]
HOSTS_LIST: [k8s_master, k8s_work, proxy, etcd]

# SITE_INFO 下面一层不能改变
SITE_INFO:
  k8s_master:
    master01:
      ip: 192.168.3.24

  etcd:
    etcd01:
      ip: 192.168.3.24

  k8s_work:
    work01:
      ip: 192.168.3.27
    work02:
      ip: 192.168.3.28

  proxy:
    proxy01:
      ip: 192.168.3.27
    proxy02:
      ip: 192.168.3.28

  ingress_work:
    ingress01:
      ip: 192.168.3.27

  k8s_work_add:
    work_add01:
      ip: 192.168.3.22
    work_add02:
      ip: 192.168.3.23

################################ DOCKER ##########################
# docker  systemd or  cgroupfs
CGROUP_DRIVE: "cgroupfs"

# docker cn registries
CN_REGISTRY: ["https://registry.docker-cn.com"]

# docker insecure-registries 默认禁用
# INSECURE_REGISTRIES: ["myregistrydomain.com:5000"]

# docker version 18.03.1.ce-1.el7.centos
DOCKER_VERSION: "18.03.1.ce-1.el7.centos"

# docker work dir default /var/lib/docker
# 当启用了此项配置，会为docker配置data目录指向
DOCKER_WORK: "/data/docker"

################################ TIME INFO ##########################
# set time tag
# 默认支持配置系统时间同步
TIME:
  tag: true
  server: "0.centos.pool.ntp.org"

################################ KERNEL INFO ##########################
# kernetl tag default false, if you want to update kernel; need set it true
# 程序提供升级Linux内核为最新，默认关闭
KERNEL_TAG: false
